### ISSUE TITLE
Not Working On Mobile

### ISSUE THREAD

**Issue by phuoctuong** [keppelen/react-facebook-login#146]
Hello,
I have a problem when i implement this package into my project.
Everything fine if i my project run in browser desktop but it's not working in browser mobile.
Can you help this ?
Thanks

**Comment by soldiercnorm** [comment]
Im having this issue as well

**Comment by talbenbasat** [comment]
me too

**Comment by AnupatRuangsuwan** [comment]
+1

**Comment by Abhijeetjaiswalit** [comment]
same issue here..

**Comment by talbenbasat** [comment]
Hi,

this is related to #124,

I used what is over there and used disableMobileRedirect={true}
this solved my problem

Tal

**Comment by keppelen** [comment]
Fix solved in new version

**Comment by XPLOT1ON** [comment]
@keppelen Is the fix release on NPM? I am still getting the error without `disableMobileRedirect={true}`

**Comment by cristiano182** [comment]
> Fix solved in new version

Thannksss alot
